name: Semgrep

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.py'         # Include Python files if your repo has Python code
      - '**/*.js'         # Include JavaScript files if applicable
      - '**/*.html'       # Include HTML files if applicable
      - '**/*.css'        # Include CSS files if applicable
      - '.github/workflows/semgrep.yml'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Semgrep Agent
      run: pip install semgrep-agent

    - name: Run Semgrep Agent
      run: semgrep-agent --config auto --baseline-ref $(git rev-parse origin/main)
